/** Legacy built-in templates (c–r) with categories for gallery filtering. */

export const LEGACY_TEMPLATE_REGISTRY = [
  {
    file: 'template-c-viral.html',
    id: 'viral-shock-card',
    name: 'Viral / Shock',
    category: 'pop-culture-media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'BADGE', label: 'Badge', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-d-highlight.html',
    id: 'highlight-wire-card',
    name: 'Highlight / Wire',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'TAG', label: 'Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SUBTEXT', label: 'Subtext', type: 'textarea', required: false },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-e-banner.html',
    id: 'banner-bold-card',
    name: 'Banner / Bold',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'BANNER_TEXT', label: 'Banner Text', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-f-stamp.html',
    id: 'stamp-breaking-card',
    name: 'Stamp / Breaking',
    category: 'pop-culture-media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'DATELINE', label: 'Dateline', type: 'text', required: false },
      { key: 'STAMP_TEXT', label: 'Stamp Text', type: 'text', required: true },
      { key: 'HEADLINE_BIG', label: 'Headline Big', type: 'text', required: true },
      { key: 'HEADLINE_ACCENT', label: 'Headline Accent', type: 'text', required: false },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-g-news-update.html',
    id: 'news-update-card',
    name: 'News Update',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-h-entertainment-scoop.html',
    id: 'entertainment-scoop-card',
    name: 'Entertainment Scoop',
    category: 'pop-culture-media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO_LEFT', label: 'Left Photo', type: 'image', required: true },
      { key: 'PHOTO_RIGHT', label: 'Right Photo', type: 'image', required: true },
      { key: 'TOP_TEXT', label: 'Top Text', type: 'textarea', required: true },
      { key: 'BOTTOM_TEXT', label: 'Bottom Text', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-i-infographic-breakdown.html',
    id: 'infographic-breakdown-card',
    name: 'Infographic Breakdown',
    category: 'tech-saas',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Title', type: 'text', required: true },
      { key: 'SECTION1_ICON', label: 'Section 1 Icon', type: 'text', required: true },
      { key: 'SECTION1_HEADING', label: 'Section 1 Heading', type: 'text', required: true },
      { key: 'SECTION1_DESC', label: 'Section 1 Description', type: 'textarea', required: false },
      { key: 'SECTION2_ICON', label: 'Section 2 Icon', type: 'text', required: true },
      { key: 'SECTION2_HEADING', label: 'Section 2 Heading', type: 'text', required: true },
      { key: 'SECTION2_DESC', label: 'Section 2 Description', type: 'textarea', required: false },
      { key: 'SECTION3_ICON', label: 'Section 3 Icon', type: 'text', required: true },
      { key: 'SECTION3_HEADING', label: 'Section 3 Heading', type: 'text', required: true },
      { key: 'SECTION3_DESC', label: 'Section 3 Description', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-j-quote-of-the-day.html',
    id: 'quote-of-the-day-card',
    name: 'Quote of the Day',
    category: 'productivity-work',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: true },
      { key: 'AUTHOR', label: 'Author', type: 'text', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-k-daily-tips.html',
    id: 'daily-tips-card',
    name: 'Daily Tips',
    category: 'productivity-work',
    previewBucket: 'square',
    fields: [
      { key: 'HEADER', label: 'Header', type: 'text', required: true },
      { key: 'PHOTO_1', label: 'Tip 1 Photo', type: 'image', required: true },
      { key: 'TIP1_ICON', label: 'Tip 1 Icon', type: 'text', required: false },
      { key: 'TIP1_TITLE', label: 'Tip 1 Title', type: 'text', required: true },
      { key: 'TIP1_DESC', label: 'Tip 1 Description', type: 'textarea', required: false },
      { key: 'PHOTO_2', label: 'Tip 2 Photo', type: 'image', required: true },
      { key: 'TIP2_ICON', label: 'Tip 2 Icon', type: 'text', required: false },
      { key: 'TIP2_TITLE', label: 'Tip 2 Title', type: 'text', required: true },
      { key: 'TIP2_DESC', label: 'Tip 2 Description', type: 'textarea', required: false },
      { key: 'PHOTO_3', label: 'Tip 3 Photo', type: 'image', required: true },
      { key: 'TIP3_ICON', label: 'Tip 3 Icon', type: 'text', required: false },
      { key: 'TIP3_TITLE', label: 'Tip 3 Title', type: 'text', required: true },
      { key: 'TIP3_DESC', label: 'Tip 3 Description', type: 'textarea', required: false },
      { key: 'PHOTO_4', label: 'Tip 4 Photo', type: 'image', required: true },
      { key: 'TIP4_ICON', label: 'Tip 4 Icon', type: 'text', required: false },
      { key: 'TIP4_TITLE', label: 'Tip 4 Title', type: 'text', required: true },
      { key: 'TIP4_DESC', label: 'Tip 4 Description', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-l-fact-of-the-day.html',
    id: 'fact-of-the-day-card',
    name: 'Fact of the Day',
    category: 'science-space',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'FACT', label: 'Fact', type: 'textarea', required: true },
      { key: 'CAPTION', label: 'Caption', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-m-comparison-challenge.html',
    id: 'comparison-challenge-card',
    name: 'Comparison Challenge',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'TITLE', label: 'Title', type: 'text', required: true },
      { key: 'PHOTO_LEFT', label: 'Left Photo', type: 'image', required: true },
      { key: 'LEFT_TITLE', label: 'Left Title', type: 'text', required: true },
      { key: 'LEFT_FEATURES', label: 'Left Features', type: 'textarea', required: false },
      { key: 'LEFT_RATING', label: 'Left Rating', type: 'text', required: false },
      { key: 'PHOTO_RIGHT', label: 'Right Photo', type: 'image', required: true },
      { key: 'RIGHT_TITLE', label: 'Right Title', type: 'text', required: true },
      { key: 'RIGHT_FEATURES', label: 'Right Features', type: 'textarea', required: false },
      { key: 'RIGHT_RATING', label: 'Right Rating', type: 'text', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-n-celebrity-profile.html',
    id: 'celebrity-profile-card',
    name: 'Celebrity Profile',
    category: 'pop-culture-media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'NAME', label: 'Name', type: 'text', required: true },
      { key: 'PROFESSION', label: 'Profession', type: 'text', required: true },
      { key: 'BIO', label: 'Biography', type: 'textarea', required: false },
      { key: 'FACTS', label: 'Facts', type: 'textarea', required: false },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-o-movie-rating.html',
    id: 'movie-rating-card',
    name: 'Movie Rating',
    category: 'pop-culture-media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Scene Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Movie Title', type: 'text', required: true },
      { key: 'GENRE', label: 'Genre', type: 'text', required: true },
      { key: 'RATING', label: 'Rating', type: 'text', required: true },
      { key: 'SUMMARY', label: 'Summary', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-p-nature-walk.html',
    id: 'nature-walk-card',
    name: 'Nature Walk Findings',
    category: 'adventure-travel',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Scene Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Title', type: 'text', required: true },
      { key: 'WALK_DESC', label: 'Walk Description', type: 'textarea', required: false },
      { key: 'FINDING1_ICON', label: 'Finding 1 Icon', type: 'text', required: false },
      { key: 'FINDING1', label: 'Finding 1', type: 'text', required: true },
      { key: 'FINDING2_ICON', label: 'Finding 2 Icon', type: 'text', required: false },
      { key: 'FINDING2', label: 'Finding 2', type: 'text', required: true },
      { key: 'FINDING3_ICON', label: 'Finding 3 Icon', type: 'text', required: false },
      { key: 'FINDING3', label: 'Finding 3', type: 'text', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-q-space-fact.html',
    id: 'space-fact-card',
    name: 'Space Fact of the Week',
    category: 'science-space',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Space Photo', type: 'image', required: true },
      { key: 'FACT', label: 'Fact', type: 'textarea', required: true },
      { key: 'EXPLANATION', label: 'Explanation', type: 'textarea', required: false },
      { key: 'MORE_INFO', label: 'More Info', type: 'text', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-r-general-info.html',
    id: 'general-info-card',
    name: 'General Information',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Title', type: 'textarea', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'text', required: false },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
];
