/** Legacy built-in templates (c–r + template-v1.1 news/media cards) with categories for gallery filtering. */

export const LEGACY_TEMPLATE_REGISTRY = [
  {
    file: 'template-c-viral.html',
    id: 'viral-shock-card',
    name: 'Viral / Shock',
    category: 'pop-culture',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'BADGE', label: 'Badge', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-d-highlight.html',
    id: 'highlight-wire-card',
    name: 'Highlight / Wire',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'TAG', label: 'Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SUBTEXT', label: 'Subtext', type: 'textarea', required: false },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-e-banner.html',
    id: 'banner-bold-card',
    name: 'Banner / Bold',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'BANNER_TEXT', label: 'Banner Text', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-f-stamp.html',
    id: 'stamp-breaking-card',
    name: 'Stamp / Breaking',
    category: 'pop-culture',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'DATELINE', label: 'Dateline', type: 'text', required: false },
      { key: 'STAMP_TEXT', label: 'Stamp Text', type: 'text', required: true },
      { key: 'HEADLINE_BIG', label: 'Headline Big', type: 'text', required: true },
      { key: 'HEADLINE_ACCENT', label: 'Headline Accent', type: 'text', required: false },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'SOURCE', label: 'Source', type: 'text', required: false },
    ],
  },
  {
    file: 'template-g-news-update.html',
    id: 'news-update-card',
    name: 'News Update',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-h-entertainment-scoop.html',
    id: 'entertainment-scoop-card',
    name: 'Entertainment Scoop',
    category: 'pop-culture',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO_LEFT', label: 'Left Photo', type: 'image', required: true },
      { key: 'PHOTO_RIGHT', label: 'Right Photo', type: 'image', required: true },
      { key: 'TOP_TEXT', label: 'Top Text', type: 'textarea', required: true },
      { key: 'BOTTOM_TEXT', label: 'Bottom Text', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-i-infographic-breakdown.html',
    id: 'infographic-breakdown-card',
    name: 'Infographic Breakdown',
    category: 'tech',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Title', type: 'text', required: true },
      { key: 'SECTION1_ICON', label: 'Section 1 Icon', type: 'text', required: true },
      { key: 'SECTION1_HEADING', label: 'Section 1 Heading', type: 'text', required: true },
      { key: 'SECTION1_DESC', label: 'Section 1 Description', type: 'textarea', required: false },
      { key: 'SECTION2_ICON', label: 'Section 2 Icon', type: 'text', required: true },
      { key: 'SECTION2_HEADING', label: 'Section 2 Heading', type: 'text', required: true },
      { key: 'SECTION2_DESC', label: 'Section 2 Description', type: 'textarea', required: false },
      { key: 'SECTION3_ICON', label: 'Section 3 Icon', type: 'text', required: true },
      { key: 'SECTION3_HEADING', label: 'Section 3 Heading', type: 'text', required: true },
      { key: 'SECTION3_DESC', label: 'Section 3 Description', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-j-quote-of-the-day.html',
    id: 'quote-of-the-day-card',
    name: 'Quote of the Day',
    category: 'productivity',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: true },
      { key: 'AUTHOR', label: 'Author', type: 'text', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-k-daily-tips.html',
    id: 'daily-tips-card',
    name: 'Daily Tips',
    category: 'productivity',
    previewBucket: 'square',
    fields: [
      { key: 'HEADER', label: 'Header', type: 'text', required: true },
      { key: 'PHOTO_1', label: 'Tip 1 Photo', type: 'image', required: true },
      { key: 'TIP1_ICON', label: 'Tip 1 Icon', type: 'text', required: false },
      { key: 'TIP1_TITLE', label: 'Tip 1 Title', type: 'text', required: true },
      { key: 'TIP1_DESC', label: 'Tip 1 Description', type: 'textarea', required: false },
      { key: 'PHOTO_2', label: 'Tip 2 Photo', type: 'image', required: true },
      { key: 'TIP2_ICON', label: 'Tip 2 Icon', type: 'text', required: false },
      { key: 'TIP2_TITLE', label: 'Tip 2 Title', type: 'text', required: true },
      { key: 'TIP2_DESC', label: 'Tip 2 Description', type: 'textarea', required: false },
      { key: 'PHOTO_3', label: 'Tip 3 Photo', type: 'image', required: true },
      { key: 'TIP3_ICON', label: 'Tip 3 Icon', type: 'text', required: false },
      { key: 'TIP3_TITLE', label: 'Tip 3 Title', type: 'text', required: true },
      { key: 'TIP3_DESC', label: 'Tip 3 Description', type: 'textarea', required: false },
      { key: 'PHOTO_4', label: 'Tip 4 Photo', type: 'image', required: true },
      { key: 'TIP4_ICON', label: 'Tip 4 Icon', type: 'text', required: false },
      { key: 'TIP4_TITLE', label: 'Tip 4 Title', type: 'text', required: true },
      { key: 'TIP4_DESC', label: 'Tip 4 Description', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-l-fact-of-the-day.html',
    id: 'fact-of-the-day-card',
    name: 'Fact of the Day',
    category: 'science',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'FACT', label: 'Fact', type: 'textarea', required: true },
      { key: 'CAPTION', label: 'Caption', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-m-comparison-challenge.html',
    id: 'comparison-challenge-card',
    name: 'Comparison Challenge',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'TITLE', label: 'Title', type: 'text', required: true },
      { key: 'PHOTO_LEFT', label: 'Left Photo', type: 'image', required: true },
      { key: 'LEFT_TITLE', label: 'Left Title', type: 'text', required: true },
      { key: 'LEFT_FEATURES', label: 'Left Features', type: 'textarea', required: false },
      { key: 'LEFT_RATING', label: 'Left Rating', type: 'text', required: false },
      { key: 'PHOTO_RIGHT', label: 'Right Photo', type: 'image', required: true },
      { key: 'RIGHT_TITLE', label: 'Right Title', type: 'text', required: true },
      { key: 'RIGHT_FEATURES', label: 'Right Features', type: 'textarea', required: false },
      { key: 'RIGHT_RATING', label: 'Right Rating', type: 'text', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-n-celebrity-profile.html',
    id: 'celebrity-profile-card',
    name: 'Celebrity Profile',
    category: 'pop-culture',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'NAME', label: 'Name', type: 'text', required: true },
      { key: 'PROFESSION', label: 'Profession', type: 'text', required: true },
      { key: 'BIO', label: 'Biography', type: 'textarea', required: false },
      { key: 'FACTS', label: 'Facts', type: 'textarea', required: false },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-o-movie-rating.html',
    id: 'movie-rating-card',
    name: 'Movie Rating',
    category: 'pop-culture',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Scene Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Movie Title', type: 'text', required: true },
      { key: 'GENRE', label: 'Genre', type: 'text', required: true },
      { key: 'RATING', label: 'Rating', type: 'text', required: true },
      { key: 'SUMMARY', label: 'Summary', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-p-nature-walk.html',
    id: 'nature-walk-card',
    name: 'Nature Walk Findings',
    category: 'adventure-travel',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Scene Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Title', type: 'text', required: true },
      { key: 'WALK_DESC', label: 'Walk Description', type: 'textarea', required: false },
      { key: 'FINDING1_ICON', label: 'Finding 1 Icon', type: 'text', required: false },
      { key: 'FINDING1', label: 'Finding 1', type: 'text', required: true },
      { key: 'FINDING2_ICON', label: 'Finding 2 Icon', type: 'text', required: false },
      { key: 'FINDING2', label: 'Finding 2', type: 'text', required: true },
      { key: 'FINDING3_ICON', label: 'Finding 3 Icon', type: 'text', required: false },
      { key: 'FINDING3', label: 'Finding 3', type: 'text', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-q-space-fact.html',
    id: 'space-fact-card',
    name: 'Space Fact of the Week',
    category: 'space',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Space Photo', type: 'image', required: true },
      { key: 'FACT', label: 'Fact', type: 'textarea', required: true },
      { key: 'EXPLANATION', label: 'Explanation', type: 'textarea', required: false },
      { key: 'MORE_INFO', label: 'More Info', type: 'text', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-r-general-info.html',
    id: 'general-info-card',
    name: 'General Information',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Title', type: 'textarea', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'text', required: false },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
    ],
  },
  {
    file: 'template-s-bbc-news.html',
    id: 'bbc-news-card',
    name: 'BBC News',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'BRAND', label: 'Brand', type: 'text', required: true },
      { key: 'TAG', label: 'Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-t-aljazeera.html',
    id: 'aljazeera-news-card',
    name: 'Al Jazeera',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'TAG', label: 'Tag', type: 'text', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-u-quote-overlay.html',
    id: 'quote-overlay-card',
    name: 'Quote Overlay',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: true },
      { key: 'ATTRIBUTION', label: 'Attribution', type: 'text', required: false },
      { key: 'BRAND', label: 'Brand', type: 'text', required: false },
    ],
  },
  {
    file: 'template-v-tweet-embed.html',
    id: 'tweet-embed-card',
    name: 'Tweet / X Embed',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'AVATAR', label: 'Avatar', type: 'image', required: false },
      { key: 'DISPLAY_NAME', label: 'Display Name', type: 'text', required: true },
      { key: 'HANDLE', label: 'Handle', type: 'text', required: true },
      { key: 'TWEET_TEXT', label: 'Tweet Text', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-w-ids-editorial.html',
    id: 'ids-editorial-card',
    name: 'IDS Editorial',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'INSET', label: 'Inset Photo', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'FOOTER_TAG', label: 'Footer Tag', type: 'text', required: false },
    ],
  },
  {
    file: 'template-x-sporty-breaking.html',
    id: 'sporty-breaking-card',
    name: 'SportyTV Breaking',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'INSET', label: 'Inset Photo', type: 'image', required: false },
      { key: 'HEADLINE_BIG', label: 'Big Headline', type: 'text', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'textarea', required: false },
    ],
  },
  {
    file: 'template-sky-quote.html',
    id: 'sky-quote',
    name: 'Sky Sports Quote',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'QUOTE', label: 'Quote Text', type: 'textarea', required: true },
      { key: 'CTA_TEXT', label: 'CTA Button Text', type: 'text', required: false },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
    ],
  },
  {
    file: 'template-sky-quote-circle.html',
    id: 'sky-quote-circle',
    name: 'Sky Sports Quote (Circle Inset)',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'INSET', label: 'Circle Inset Photo', type: 'image', required: false },
      { key: 'QUOTE', label: 'Quote Text', type: 'textarea', required: true },
      { key: 'ATTRIBUTION', label: 'Attribution', type: 'text', required: false },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
    ],
  },
  {
    file: 'template-sky-breaking.html',
    id: 'sky-breaking',
    name: 'Sky Sports Breaking News',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'TAG', label: 'Tag Badge', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'text', required: false },
    ],
  },
  {
    file: 'template-sky-scorecard.html',
    id: 'sky-scorecard',
    name: 'Sky Sports Scorecard',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Match Photo', type: 'image', required: true },
      { key: 'TEAM1_BADGE', label: 'Team 1 Badge', type: 'image', required: true },
      { key: 'TEAM1_SCORE', label: 'Team 1 Score', type: 'text', required: true },
      { key: 'TEAM2_BADGE', label: 'Team 2 Badge', type: 'image', required: true },
      { key: 'TEAM2_SCORE', label: 'Team 2 Score', type: 'text', required: true },
      { key: 'STATUS', label: 'Match Status', type: 'text', required: true },
    ],
  },
  {
    file: 'template-sky-statement.html',
    id: 'sky-statement',
    name: 'Sky Sports Statement',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'QUOTE', label: 'Quote / Statement', type: 'textarea', required: true },
      { key: 'ATTRIBUTION', label: 'Attribution', type: 'text', required: false },
    ],
  },
  {
    file: 'template-sky-stats.html',
    id: 'sky-stats',
    name: 'Sky Sports Stats Table',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'TITLE', label: 'Card Title', type: 'text', required: true },
      { key: 'SUBTITLE', label: 'Card Subtitle', type: 'text', required: false },
      { key: 'STAT_ROWS', label: 'Stats Rows (HTML)', type: 'textarea', required: true },
      { key: 'HIGHLIGHT_ROW', label: 'Highlighted Row Index', type: 'text', required: false },
    ],
  },
  {
    file: 'template-ronb-headline.html',
    id: 'ronb-headline',
    name: 'RONB Photo Headline',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'INSET', label: 'Inset Photo', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
    ],
  },
  {
    file: 'template-ronb-news.html',
    id: 'ronb-news',
    name: 'RONB News Overlay',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'TAG', label: 'Category Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
    ],
  },
  {
    file: 'template-ronb-banner.html',
    id: 'ronb-banner',
    name: 'RONB Text Banner',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'BANNER_TEXT', label: 'Banner Text', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
    ],
  },
  {
    file: 'template-pediastan.html',
    id: 'pediastan-news',
    name: 'PediaStan News',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'CONTACT', label: 'Contact Info', type: 'text', required: false },
    ],
  },
  {
    file: 'template-memenions.html',
    id: 'memenions',
    name: 'Memenions Highlight',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Main Photo', type: 'image', required: true },
      { key: 'INSET', label: 'Circle Inset', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'text', required: false },
      { key: 'BRAND', label: 'Brand Logo Text', type: 'text', required: false },
    ],
  },
  {
    file: 'template-dual-image-fact.html',
    id: 'dual-image-fact',
    name: 'Dual Image Fact Card',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO_LEFT', label: 'Left Image', type: 'image', required: true },
      { key: 'PHOTO_RIGHT', label: 'Right Image', type: 'image', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
    ],
  },
  {
    file: 'template-aj-economy.html',
    id: 'aj-economy',
    name: 'Al Jazeera Economy',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'AJ Logo', type: 'image', required: false },
      { key: 'TAG', label: 'Category Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-aj-explainer.html',
    id: 'aj-explainer',
    name: 'Al Jazeera Explainer',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'AJ Logo', type: 'image', required: false },
      { key: 'TAG', label: 'Hashtag Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-aj-location.html',
    id: 'aj-location',
    name: 'Al Jazeera Location',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'AJ Logo', type: 'image', required: false },
      { key: 'LOCATION', label: 'Location Name', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-ch4-promo.html',
    id: 'ch4-promo',
    name: 'Channel 4 Promo',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'BRAND', label: 'Brand Text', type: 'text', required: false },
      { key: 'TAG', label: 'Tag Badge', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-ch4-tweet.html',
    id: 'ch4-tweet',
    name: 'Channel 4 Tweet Style',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'AVATAR', label: 'Avatar', type: 'image', required: true },
      { key: 'DISPLAY_NAME', label: 'Display Name', type: 'text', required: true },
      { key: 'HANDLE', label: 'Handle', type: 'text', required: true },
      { key: 'TIME', label: 'Time', type: 'text', required: false },
      { key: 'TWEET_TEXT', label: 'Tweet Text', type: 'textarea', required: true },
      { key: 'BRAND', label: 'Brand Text', type: 'text', required: false },
    ],
  },
  {
    file: 'template-fv-story.html',
    id: 'fv-story',
    name: 'Founders Vision Story',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Main Photo', type: 'image', required: true },
      { key: 'PHOTO2', label: 'Secondary Photo', type: 'image', required: false },
      { key: 'BRAND', label: 'Brand Badge', type: 'text', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
    ],
  },
  {
    file: 'template-fv-comparison.html',
    id: 'fv-comparison',
    name: 'Founders Vision Comparison',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO_LEFT', label: 'Left Photo', type: 'image', required: true },
      { key: 'PHOTO_RIGHT', label: 'Right Photo', type: 'image', required: true },
      { key: 'LEFT_NAME', label: 'Left Name', type: 'text', required: true },
      { key: 'RIGHT_NAME', label: 'Right Name', type: 'text', required: true },
      { key: 'LEFT_STATS', label: 'Left Stats', type: 'textarea', required: true },
      { key: 'RIGHT_STATS', label: 'Right Stats', type: 'textarea', required: true },
      { key: 'BRAND', label: 'Brand Badge', type: 'text', required: false },
    ],
  },
  {
    file: 'template-sporty-news.html',
    id: 'sporty-news',
    name: 'SportyTV News',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'HEADLINE_BIG', label: 'Headline', type: 'text', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'textarea', required: false },
    ],
  },
  {
    file: 'template-sporty-scoreline.html',
    id: 'sporty-scoreline',
    name: 'SportyTV Scoreline',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'TEAM1_NAME', label: 'Team 1 Name', type: 'text', required: true },
      { key: 'TEAM1_FLAG', label: 'Team 1 Flag', type: 'image', required: true },
      { key: 'TEAM1_SCORE', label: 'Team 1 Score', type: 'text', required: true },
      { key: 'TEAM2_NAME', label: 'Team 2 Name', type: 'text', required: true },
      { key: 'TEAM2_FLAG', label: 'Team 2 Flag', type: 'image', required: true },
      { key: 'TEAM2_SCORE', label: 'Team 2 Score', type: 'text', required: true },
      { key: 'STATUS', label: 'Status (e.g. FT)', type: 'text', required: true },
      { key: 'MATCH_TYPE', label: 'Match Type', type: 'text', required: false },
      { key: 'SCORERS', label: 'Goal Scorers', type: 'textarea', required: false },
    ],
  },
  {
    file: 'template-sporty-stats.html',
    id: 'sporty-stats',
    name: 'SportyTV Stats Table',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'HEADLINE_BIG', label: 'Headline', type: 'text', required: true },
      { key: 'SUBTITLE', label: 'Subtitle', type: 'textarea', required: false },
      { key: 'STAT_ROWS', label: 'Stats Table Rows', type: 'textarea', required: true },
    ],
  },
  {
    file: 'template-ids-multi.html',
    id: 'ids-multi',
    name: 'IDS Multi-Inset Editorial',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Brand Logo', type: 'image', required: false },
      { key: 'INSET_LEFT', label: 'Left Inset Photo', type: 'image', required: false },
      { key: 'INSET_RIGHT', label: 'Right Inset Photo', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
      { key: 'FOOTER_TAG', label: 'Footer Tag', type: 'text', required: false },
    ],
  },
  {
    file: 'template-ids-sponsor.html',
    id: 'ids-sponsor',
    name: 'IDS with Sponsor',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'SPONSOR_LOGO', label: 'Sponsor Logo', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'SPONSOR_BANNER', label: 'Sponsor Banner', type: 'image', required: false },
    ],
  },
  {
    file: 'template-fact-inset.html',
    id: 'fact-inset',
    name: 'Fact Card with Circle Inset',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'INSET', label: 'Circle Inset Photo', type: 'image', required: false },
      { key: 'BRAND', label: 'Brand Initials', type: 'text', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
    ],
  },
  {
    file: 'template-fact-warning.html',
    id: 'fact-warning',
    name: 'Fact Warning / Explainer',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Background Photo', type: 'image', required: true },
      { key: 'INSET', label: 'Inset Photo', type: 'image', required: false },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'DESCRIPTION', label: 'Description', type: 'textarea', required: false },
    ],
  },
  {
    file: 'carousel-cover-swipe.html',
    id: 'carousel-cover-swipe',
    name: 'Carousel Cover Swipe',
    category: 'media',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'SWIPE_LABEL', label: 'Swipe Label', type: 'text', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'celeb-content.html',
    id: 'celeb-content',
    name: 'Celebrity Content',
    category: 'pop-culture',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'NAME', label: 'Name', type: 'text', required: true },
      { key: 'CAPTION', label: 'Caption', type: 'textarea', required: true },
    ],
  },
  {
    file: 'celeb-cover.html',
    id: 'celeb-cover',
    name: 'Celebrity Cover',
    category: 'pop-culture',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'comparison-side.html',
    id: 'comparison-side',
    name: 'Side by Side Comparison',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO_1', label: 'Photo 1', type: 'image', required: true },
      { key: 'PHOTO_2', label: 'Photo 2', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'FLAG_1', label: 'Flag 1', type: 'image', required: false },
      { key: 'NAME_1', label: 'Name 1', type: 'text', required: true },
      { key: 'FLAG_2', label: 'Flag 2', type: 'image', required: false },
      { key: 'NAME_2', label: 'Name 2', type: 'text', required: true },
    ],
  },
  {
    file: 'fact-post-social.html',
    id: 'fact-post-social',
    name: 'Fact Post with Social Icons',
    category: 'general',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'facts-content-caption.html',
    id: 'facts-content-caption',
    name: 'Facts Content with Caption',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'CAPTION', label: 'Caption', type: 'textarea', required: true },
    ],
  },
  {
    file: 'facts-cover-grid.html',
    id: 'facts-cover-grid',
    name: 'Facts Cover Grid',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO_1', label: 'Photo 1', type: 'image', required: true },
      { key: 'PHOTO_2', label: 'Photo 2', type: 'image', required: true },
      { key: 'PHOTO_3', label: 'Photo 3', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'news-bulletin-ribbon.html',
    id: 'news-bulletin-ribbon',
    name: 'News Bulletin with Ribbon',
    category: 'media',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'WATERMARK_TEXT', label: 'Watermark Text', type: 'text', required: false },
      { key: 'TAG', label: 'Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
      { key: 'BODY', label: 'Body', type: 'textarea', required: false },
      { key: 'URL', label: 'URL', type: 'text', required: false },
    ],
  },
  {
    file: 'news-card-breaking.html',
    id: 'news-card-breaking',
    name: 'News Card Breaking',
    category: 'media',
    previewBucket: 'story',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'MASTHEAD', label: 'Masthead', type: 'text', required: true },
      { key: 'TAG', label: 'Tag', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'news-card-plain.html',
    id: 'news-card-plain',
    name: 'News Card Plain',
    category: 'media',
    previewBucket: 'story',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'MASTHEAD', label: 'Masthead', type: 'text', required: true },
      { key: 'HEADLINE', label: 'Headline', type: 'textarea', required: true },
    ],
  },
  {
    file: 'quote-highlight.html',
    id: 'quote-highlight',
    name: 'Quote Highlight',
    category: 'general',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: true },
    ],
  },
  {
    file: 'split-before-after.html',
    id: 'split-before-after',
    name: 'Split Before / After',
    category: 'general',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO_1', label: 'Before Photo', type: 'image', required: true },
      { key: 'LABEL_1', label: 'Before Label', type: 'text', required: true },
      { key: 'CAPTION_1', label: 'Before Caption', type: 'textarea', required: false },
      { key: 'PHOTO_2', label: 'After Photo', type: 'image', required: true },
      { key: 'LABEL_2', label: 'After Label', type: 'text', required: true },
      { key: 'CAPTION_2', label: 'After Caption', type: 'textarea', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'HANDLE', label: 'Handle', type: 'text', required: false },
    ],
  },
  {
    file: 'stacked-list-5row.html',
    id: 'stacked-list-5row',
    name: 'Stacked List (5 Rows)',
    category: 'general',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO_1', label: 'Row 1 Photo', type: 'image', required: true },
      { key: 'TITLE_1', label: 'Row 1 Title', type: 'text', required: true },
      { key: 'TAG_1', label: 'Row 1 Tag', type: 'text', required: false },
      { key: 'PHOTO_2', label: 'Row 2 Photo', type: 'image', required: true },
      { key: 'TITLE_2', label: 'Row 2 Title', type: 'text', required: true },
      { key: 'TAG_2', label: 'Row 2 Tag', type: 'text', required: false },
      { key: 'PHOTO_3', label: 'Row 3 Photo', type: 'image', required: true },
      { key: 'TITLE_3', label: 'Row 3 Title', type: 'text', required: true },
      { key: 'TAG_3', label: 'Row 3 Tag', type: 'text', required: false },
      { key: 'PHOTO_4', label: 'Row 4 Photo', type: 'image', required: true },
      { key: 'TITLE_4', label: 'Row 4 Title', type: 'text', required: true },
      { key: 'TAG_4', label: 'Row 4 Tag', type: 'text', required: false },
      { key: 'PHOTO_5', label: 'Row 5 Photo', type: 'image', required: true },
      { key: 'TITLE_5', label: 'Row 5 Title', type: 'text', required: true },
      { key: 'TAG_5', label: 'Row 5 Tag', type: 'text', required: false },
    ],
  },
  {
    file: 'story-badge-insets.html',
    id: 'story-badge-insets',
    name: 'Story Card with Badge & Insets',
    category: 'media',
    previewBucket: 'portrait',
    fields: [
      { key: 'PHOTO_MAIN', label: 'Main Photo', type: 'image', required: true },
      { key: 'PHOTO_INSET_1', label: 'Inset Photo 1', type: 'image', required: false },
      { key: 'PHOTO_INSET_2', label: 'Inset Photo 2', type: 'image', required: false },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'BRAND', label: 'Brand Name', type: 'text', required: false },
      { key: 'FOLLOW_TEXT', label: 'Follow Button Text', type: 'text', required: false },
      { key: 'CAPTION', label: 'Caption', type: 'textarea', required: true },
    ],
  },
  {
    file: 'tsn-quote-fullbleed.html',
    id: 'tsn-quote-fullbleed',
    name: 'TSN Quote Full Bleed',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'TOP_TAG', label: 'Top Tag', type: 'text', required: false },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: true },
      { key: 'CAPTION', label: 'Caption', type: 'textarea', required: false },
    ],
  },
  {
    file: 'tsn-quote-split.html',
    id: 'tsn-quote-split',
    name: 'TSN Quote Split',
    category: 'media',
    previewBucket: 'square',
    fields: [
      { key: 'PHOTO', label: 'Photo', type: 'image', required: true },
      { key: 'LOGO', label: 'Logo', type: 'image', required: false },
      { key: 'QUOTE', label: 'Quote', type: 'textarea', required: true },
      { key: 'CAPTION', label: 'Caption', type: 'textarea', required: false },
    ],
  },
];
